### ISSUE TITLE
请问有实体的数据库查询语句吗

### ISSUE THREAD

**Issue by ugod3** [LiuXIn011/rightHouse#2]

**Comment by LiuXIn011** [comment]
数据库是基于Sequelize，文档已经在路上了，点个star不迷路

**Comment by ugod3** [comment]
我现在运行卡在阿里云的短信服务了
报了个这个提示
AssertionError [ERR_ASSERTION]: [egg-sms] Must set `accessKeyId` and `secretAccessKey` in sms's config
这个项目需要搭载这个服务吗

**Comment by LiuXIn011** [comment]
建议你等一下文档哦，配置还是很多的。

**Comment by ugod3** [comment]
好的，感谢

**Comment by LiuXIn011** [comment]
文档https://liuxin011.github.io/RH-doc-release/

**Comment by ugod3** [comment]
你好，我想问不搭载小程序需要适配redis吗

**Comment by LiuXIn011** [comment]
需要关闭redis插件 否则会报错

**Comment by ugod3** [comment]
在项目中哪些文件里有redis呢，试了几次会redis报错

**Comment by ugod3** [comment]
![图片](https://github.com/LiuXIn011/rightHouse/assets/53908829/3ef56158-b55a-4606-8823-ade3ab1418f9)

**Comment by LiuXIn011** [comment]
短信服务如果不用的话需要关掉
![image](https://github.com/LiuXIn011/rightHouse/assets/48080203/5171832d-01d6-4821-bbc7-d037d640a22c)
redis存储微信开放平台的token，redis是必要的组件。

**Comment by ugod3** [comment]
搭载在网页上可以不用到redis吗

**Comment by LiuXIn011** [comment]
你可以试一下，还是在plugin,js内把redis配置注释掉

**Comment by ugod3** [comment]
PS D:\上课\项目\rightHouse-develop\RH-server> npm run dev

> app@1.0.0 dev
> egg-bin dev

[egg-ts-helper] create typings\app\controller\index.d.ts (4ms)
[egg-ts-helper] create typings\app\middleware\index.d.ts (3ms)
[egg-ts-helper] create typings\app\model\index.d.ts (3ms)
[egg-ts-helper] create typings\config\index.d.ts (36ms)
[egg-ts-helper] create typings\config\plugin.d.ts (2ms)
[egg-ts-helper] create typings\app\service\index.d.ts (3ms)
[egg-ts-helper] create typings\app\index.d.ts (1ms)
2023-05-29 16:03:23,604 INFO 11768 [master] node version v16.20.0
2023-05-29 16:03:23,605 INFO 11768 [master] egg version 3.16.0
[egg-ts-helper] create typings\app\controller\index.d.ts (2ms)
[egg-ts-helper] create typings\app\middleware\index.d.ts (5ms)
[egg-ts-helper] create typings\app\model\index.d.ts (4ms)
[egg-ts-helper] create typings\config\index.d.ts (29ms)
[egg-ts-helper] create typings\config\plugin.d.ts (2ms)
[egg-ts-helper] create typings\app\service\index.d.ts (3ms)
[egg-ts-helper] create typings\app\index.d.ts (2ms)
2023-05-29 16:03:26,943 INFO 13012 [egg-sequelize](2ms) Executed (default): SELECT 1+1 AS result
2023-05-29 16:03:26,949 INFO 11768 [master] agent_worker#1:13012 started (3339ms)
2023-05-29 16:03:29,223 ERROR 19704 nodejs.Error: secret should be set
    at module.exports (D:\上课\项目\rightHouse-develop\RH-server\node_modules\koa-jwt2\lib\index.js:21:42)
    at module.exports (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-jwt\app\middleware\jwt.js:6:10)
    at AppWorkerLoader.loadMiddleware (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-core\lib\loader\mixin\middleware.js:75:12)
    at AppWorkerLoader.load (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg\lib\loader\app_worker_loader.js:39:10)
    at new Application (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg\lib\application.js:66:19)
    at Object.<anonymous> (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-cluster\lib\app_worker.js:29:9)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)

pid: 19704
hostname: LAPTOP-GUGD210E

D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-cluster\lib\app_worker.js:32
  throw err;
  ^

Error: secret should be set
    at module.exports (D:\上课\项目\rightHouse-develop\RH-server\node_modules\koa-jwt2\lib\index.js:21:42)
    at module.exports (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-jwt\app\middleware\jwt.js:6:10)
    at AppWorkerLoader.loadMiddleware (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-core\lib\loader\mixin\middleware.js:75:12)
    at AppWorkerLoader.load (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg\lib\loader\app_worker_loader.js:39:10)
    at new Application (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg\lib\application.js:66:19)
    at Object.<anonymous> (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-cluster\lib\app_worker.js:29:9)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
[2023-05-29 16:03:29.246] [cfork:master:11768] worker:19704 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
[2023-05-29 16:03:29.248] [cfork:master:11768] don't fork, because worker:19704 will be kill soon  
2023-05-29 16:03:29,248 INFO 11768 [master] app_worker#1:19704 disconnect, suicide: false, state: disconnected, current workers: ["1"]
[2023-05-29 16:03:29.272] [cfork:master:11768] worker:19704 exit (code: 1, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
2023-05-29 16:03:29,275 ERROR 11768 nodejs.AppWorkerDiedError: [master] app_worker#1:19704 died (code: undefined, signal: null, suicide: false, state: dead), current workers: [19704]
    at Master.onAppExit (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-cluster\lib\master.js:401:21)
    at Master.emit (node:events:513:28)
    at Messenger.sendToMaster (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-cluster\lib\utils\messenger.js:137:17)
    at Messenger.send (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-cluster\lib\utils\messenger.js:102:12)
    at EventEmitter.<anonymous> (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-cluster\lib\utils\mode\impl\process\app.js:114:22)
    at EventEmitter.emit (node:events:525:35)
    at ChildProcess.<anonymous> (node:internal/cluster/primary:188:13)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
name: "AppWorkerDiedError"
pid: 11768
hostname: LAPTOP-GUGD210E

2023-05-29 16:03:29,281 ERROR 11768 [master] app_worker#1:19704 start fail, exiting with code:1
2023-05-29 16:03:29,282 ERROR 11768 [master] exit with code:1
Error: D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-bin\lib\start-cluster {"declarations":true,"tsconfigPaths":true,"tsconfig-paths":true,"tscompiler":"D:\\上课\\项目\\rightHouse-develop\\RH-server\\node_modules\\ts-node\\register\\index.js","eggTsHelper":"D:\\ 
上课\\项目\\rightHouse-develop\\RH-server\\node_modules\\egg-ts-helper\\register.js","workers":1,"baseDir":"D:\\上课\\项目\\rightHouse-develop\\RH-server","framework":"D:\\上课\\项目\\rightHouse-develop\\RH-server\\node_modules\\egg"} exit with code 1
    at ChildProcess.<anonymous> (D:\上课\项目\rightHouse-develop\RH-server\node_modules\common-bin\lib\helper.js:56:21)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12) {
  code: 1
}

**Comment by ugod3** [comment]
看报错好像是egg的脚本文件参数没设置

**Comment by ugod3** [comment]
``PS D:\上课\项目\rightHouse-develop\RH-server> npm run dev

> app@1.0.0 dev
> egg-bin dev

[egg-ts-helper] create typings\app\controller\index.d.ts (2ms)
[egg-ts-helper] create typings\app\middleware\index.d.ts (3ms)
[egg-ts-helper] create typings\app\model\index.d.ts (3ms)
[egg-ts-helper] create typings\config\index.d.ts (27ms)
[egg-ts-helper] create typings\config\plugin.d.ts (1ms)
[egg-ts-helper] create typings\app\service\index.d.ts (2ms)
[egg-ts-helper] create typings\app\index.d.ts (2ms)
2023-05-29 15:42:57,915 INFO 10188 [master] node version v16.20.0
2023-05-29 15:42:57,916 INFO 10188 [master] egg version 3.16.0
[egg-ts-helper] create typings\app\controller\index.d.ts (3ms)
[egg-ts-helper] create typings\app\middleware\index.d.ts (2ms)
[egg-ts-helper] create typings\app\model\index.d.ts (2ms)
[egg-ts-helper] create typings\config\index.d.ts (30ms)
[egg-ts-helper] create typings\config\plugin.d.ts (2ms)
[egg-ts-helper] create typings\app\service\index.d.ts (2ms)
[egg-ts-helper] create typings\app\index.d.ts (0ms)
2023-05-29 15:43:00,489 INFO 22816 [egg-sequelize](2ms) Executed (default): SELECT 1+1 AS result
2023-05-29 15:43:00,494 INFO 10188 [master] agent_worker#1:22816 started (2572ms)
2023-05-29 15:43:02,596 ERROR 14024 nodejs.Error: secret should be set
    at module.exports (D:\上课\项目\rightHouse-develop\RH-server\node_modules\koa-jwt2\lib\index.js:21:42)
    at module.exports (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-jwt\app\middleware\jwt.js:6:10)
    at AppWorkerLoader.loadMiddleware (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-core\lib\loader\mixin\middleware.js:75:12)
    at AppWorkerLoader.load (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg\lib\loader\app_worker_loader.js:39:10)
    at new Application (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg\lib\application.js:66:19)
    at Object.<anonymous> (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-cluster\lib\app_worker.js:29:9)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)

pid: 14024
hostname: LAPTOP-GUGD210E

D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-cluster\lib\app_worker.js:32
  throw err;
  ^

Error: secret should be set
    at module.exports (D:\上课\项目\rightHouse-develop\RH-server\node_modules\koa-jwt2\lib\index.js:21:42)
    at module.exports (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-jwt\app\middleware\jwt.js:6:10)
    at AppWorkerLoader.loadMiddleware (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-core\lib\loader\mixin\middleware.js:75:12)
    at AppWorkerLoader.load (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg\lib\loader\app_worker_loader.js:39:10)
    at new Application (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg\lib\application.js:66:19)
    at Object.<anonymous> (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-cluster\lib\app_worker.js:29:9)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
[2023-05-29 15:43:02.610] [cfork:master:10188] worker:14024 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
[2023-05-29 15:43:02.611] [cfork:master:10188] don't fork, because worker:14024 will be kill soon  
2023-05-29 15:43:02,611 INFO 10188 [master] app_worker#1:14024 disconnect, suicide: false, state: disconnected, current workers: ["1"]
[2023-05-29 15:43:02.632] [cfork:master:10188] worker:14024 exit (code: 1, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
2023-05-29 15:43:02,639 ERROR 10188 nodejs.AppWorkerDiedError: [master] app_worker#1:14024 died (code: undefined, signal: null, suicide: false, state: dead), current workers: [14024]
    at Master.onAppExit (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-cluster\lib\master.js:401:21)
    at Master.emit (node:events:513:28)
    at Messenger.sendToMaster (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-cluster\lib\utils\messenger.js:137:17)
    at Messenger.send (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-cluster\lib\utils\messenger.js:102:12)
    at EventEmitter.<anonymous> (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-cluster\lib\utils\mode\impl\process\app.js:114:22)
    at EventEmitter.emit (node:events:525:35)
    at ChildProcess.<anonymous> (node:internal/cluster/primary:188:13)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
name: "AppWorkerDiedError"
pid: 10188
hostname: LAPTOP-GUGD210E

2023-05-29 15:43:02,643 ERROR 10188 [master] app_worker#1:14024 start fail, exiting with code:1    
2023-05-29 15:43:02,644 ERROR 10188 [master] exit with code:1
Error: D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-bin\lib\start-cluster {"declaratiop\\RH-server\\node_modules\\ts-node\\register\\index.js","eggTsHelper":"D:\\上课\\项目\\rightHouse-develop\\RH-server\\node_modules\\egg-ts-helper\\register.js","workers":1,"baseDir":"D:\\上课\\项 
目\\rightHouse-develop\\RH-server","framework":"D:\\上课\\项目\\rightHouse-develop\\RH-server\\node_modules\\egg"} exit with code 1
    at ChildProcess.<anonymous> (D:\上课\项目\rightHouse-develop\RH-server\node_modules\common-bin\lib\helper.js:56:21)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12) {
  code: 1
}
PS D:\上课\项目\rightHouse-develop\RH-server> npm run dev

> app@1.0.0 dev
> egg-bin dev

[egg-ts-helper] create typings\app\controller\index.d.ts (4ms)
[egg-ts-helper] create typings\app\middleware\index.d.ts (3ms)
[egg-ts-helper] create typings\app\model\index.d.ts (3ms)
[egg-ts-helper] create typings\config\index.d.ts (36ms)
[egg-ts-helper] create typings\config\plugin.d.ts (2ms)
[egg-ts-helper] create typings\app\service\index.d.ts (3ms)
[egg-ts-helper] create typings\app\index.d.ts (1ms)
2023-05-29 16:03:23,604 INFO 11768 [master] node version v16.20.0
2023-05-29 16:03:23,605 INFO 11768 [master] egg version 3.16.0
[egg-ts-helper] create typings\app\controller\index.d.ts (2ms)
[egg-ts-helper] create typings\app\middleware\index.d.ts (5ms)
[egg-ts-helper] create typings\app\model\index.d.ts (4ms)
[egg-ts-helper] create typings\config\index.d.ts (29ms)
[egg-ts-helper] create typings\config\plugin.d.ts (2ms)
[egg-ts-helper] create typings\app\service\index.d.ts (3ms)
[egg-ts-helper] create typings\app\index.d.ts (2ms)
2023-05-29 16:03:26,943 INFO 13012 [egg-sequelize](2ms) Executed (default): SELECT 1+1 AS result
2023-05-29 16:03:26,949 INFO 11768 [master] agent_worker#1:13012 started (3339ms)
2023-05-29 16:03:29,223 ERROR 19704 nodejs.Error: secret should be set
    at module.exports (D:\上课\项目\rightHouse-develop\RH-server\node_modules\koa-jwt2\lib\index.js:21:42)
    at module.exports (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-jwt\app\middleware\jwt.js:6:10)
    at AppWorkerLoader.loadMiddleware (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-core\lib\loader\mixin\middleware.js:75:12)
    at AppWorkerLoader.load (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg\lib\loader\app_worker_loader.js:39:10)
    at new Application (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg\lib\application.js:66:19)
    at Object.<anonymous> (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-cluster\lib\app_worker.js:29:9)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)

pid: 19704
hostname: LAPTOP-GUGD210E

D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-cluster\lib\app_worker.js:32
  throw err;
  ^

Error: secret should be set
    at module.exports (D:\上课\项目\rightHouse-develop\RH-server\node_modules\koa-jwt2\lib\index.js:21:42)
    at module.exports (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-jwt\app\middleware\jwt.js:6:10)
    at AppWorkerLoader.loadMiddleware (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-core\lib\loader\mixin\middleware.js:75:12)
    at AppWorkerLoader.load (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg\lib\loader\app_worker_loader.js:39:10)
    at new Application (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg\lib\application.js:66:19)
    at Object.<anonymous> (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-cluster\lib\app_worker.js:29:9)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
[2023-05-29 16:03:29.246] [cfork:master:11768] worker:19704 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
[2023-05-29 16:03:29.248] [cfork:master:11768] don't fork, because worker:19704 will be kill soon  
2023-05-29 16:03:29,248 INFO 11768 [master] app_worker#1:19704 disconnect, suicide: false, state: disconnected, current workers: ["1"]
[2023-05-29 16:03:29.272] [cfork:master:11768] worker:19704 exit (code: 1, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
2023-05-29 16:03:29,275 ERROR 11768 nodejs.AppWorkerDiedError: [master] app_worker#1:19704 died (code: undefined, signal: null, suicide: false, state: dead), current workers: [19704]
    at Master.onAppExit (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-cluster\lib\master.js:401:21)
    at Master.emit (node:events:513:28)
    at Messenger.sendToMaster (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-cluster\lib\utils\messenger.js:137:17)
    at Messenger.send (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-cluster\lib\utils\messenger.js:102:12)
    at EventEmitter.<anonymous> (D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-cluster\lib\utils\mode\impl\process\app.js:114:22)
    at EventEmitter.emit (node:events:525:35)
    at ChildProcess.<anonymous> (node:internal/cluster/primary:188:13)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
name: "AppWorkerDiedError"
pid: 11768
hostname: LAPTOP-GUGD210E

2023-05-29 16:03:29,281 ERROR 11768 [master] app_worker#1:19704 start fail, exiting with code:1
2023-05-29 16:03:29,282 ERROR 11768 [master] exit with code:1
Error: D:\上课\项目\rightHouse-develop\RH-server\node_modules\egg-bin\lib\start-cluster {"declarations":true,"tsconfigPaths":true,"tsconfig-paths":true,"tscompiler":"D:\\上课\\项目\\rightHouse-develop\\RH-server\\node_modules\\ts-node\\register\\index.js","eggTsHelper":"D:\\ 
上课\\项目\\rightHouse-develop\\RH-server\\node_modules\\egg-ts-helper\\register.js","workers":1,"baseDir":"D:\\上课\\项目\\rightHouse-develop\\RH-server","framework":"D:\\上课\\项目\\rightHouse-develop\\RH-server\\node_modules\\egg"} exit with code 1
    at ChildProcess.<anonymous> (D:\上课\项目\rightHouse-develop\RH-server\node_modules\common-bin\lib\helper.js:56:21)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12) {
  code: 1
}

**Comment by ugod3** [comment]
这上面的报错你看的清楚吗，需要以图片的形式给你看吗

**Comment by ugod3** [comment]
`/* eslint valid-jsdoc: "off" */

'use strict';

/**
 * @param {Egg.EggAppInfo} appInfo app info
 */
module.exports = appInfo => {
  const config = exports = {};
  config.keys = appInfo.name + '_1667378056410_2465';

  // 中间件列表
  config.middleware = [ 'errorHandler' ];
  // 错误处理中间件
  config.errorHandler = {
    match: '/api'
  };

  // const userConfig = {
  //   // 房东端小程序配置
  //   landlordMP: {
  //     appid: '',
  //     secret: ''
  //   },
  //   // 租客端小程序配置
  //   tenantsMP: {
  //     appid: '',
  //     secret: ''
  //   },
  //   // 上传文件目录
  //   uploadDir: 'app/public/upload',
  //   // oss配置minio
  //   minio: {
  //     endPoint: '', // 连接地址
  //     port: 9000, // 端口
  //     useSSL: false, // 不需要https
  //     accessKey: '',
  //     secretKey: '',
  //     urldomain: '', // 域名
  //     bucketName: 'filebucket' // 桶名称
  //   },
  //   // 房间报修阿里云短信通知
  //   houseMaintenanceMessage: {
  //     SignName: '',
  //     TemplateCode: ''
  //   },
  //   // 房间维修完毕阿里云短信通知
  //   houseSolveMaintenanceMessage: {
  //     SignName: '',
  //     TemplateCode: ''
  //   },
  //   // 房间入住阿里云短信通知
  //   houseJoinTenantMessage: {
  //     SignName: '',
  //     TemplateCode: ''
  //   },
  //   // 房间退租给租客的阿里云短信通知
  //   houseOutTenantMessage: {
  //     SignName: '',
  //     TemplateCode: ''
  //   },
  //   // 房间退租给房东的阿里云短信通知
  //   houseOutLandlordMessage: {
  //     SignName: '',
  //     TemplateCode: ''
  //   },
  //   // 租客申请租赁的阿里云短信通知
  //   tenantLeaseApplicationMessage: {
  //     SignName: '',
  //     TemplateCode: ''
  //   },
  //   // 房东通过租赁的阿里云短信通知
  //   passLeaseApplicationMessage: {
  //     SignName: '',
  //     TemplateCode: ''
  //   },
  //   // 房东驳回租客租赁的阿里云短信通知
  //   nopassLeaseApplicationMessage: {
  //     SignName: '',
  //     TemplateCode: ''
  //   }
  // };
  // 数据库配置
  config.sequelize = {
    dialect: 'mysql',
    host: 'localhost',
    port: 3306,
    database: 'right_house_db',
    username: 'root',
    password: 'root'
  };
  // redis配置
  // config.redis = {
  //   client: {
  //     port: 6379,
  //     host: 'localhost',
  //     password: '',
  //     db: 0 
  //   }
  // };
  // security
  config.security = {
    csrf: {
      enable: false
    }
  };
  // jwt
  config.jwt = {
    secret: '',
    sign: {
      expiresIn: 604800 // 过期时间
    }
  };
  // multipart
  config.multipart = {
    mode: 'file'
  };
  // 默认配置
  config.cluster = {
    listen: {
      port: 7001
    }
  };
  // 性能监控平台配置
  // config.alinode = {
  //   server: '',
  //   appid: '',
  //   secret: ''
  // };
  // 跨域配置
  config.cors = {
    origin: '*',
    allowMethods: 'GET,HEAD,PUT,POST,DELETE,PATCH'
  };

  // 短信服务配置
  // config.sms = {
  //   client: {
  //     accessKeyId: '',
  //     secretAccessKey: ''
  //   }
  // };
  // return {
  //   ...config,
  //   ...userConfig
  // };
};
`

这是我修改config.js后的情况

**Comment by ugod3** [comment]
![图片](https://github.com/LiuXIn011/rightHouse/assets/53908829/ea12cdb9-380f-4f23-938c-efdcfad95dc0)
// D:\上课\项目\rightHouse-develop\RH-server\config.default.js

![图片](https://github.com/LiuXIn011/rightHouse/assets/53908829/b87822f6-fd9a-4fa9-9761-2ef0812b108e)
![图片](https://github.com/LiuXIn011/rightHouse/assets/53908829/a2d1393b-71ff-42a7-9e85-afce5f2c40dd)
这里为什么会报这个错，检查了一下数据库配置是对的

**Comment by LiuXIn011** [comment]
config.default.js不需要更改什么，把注释全部放开。
如果有不用的插件，在plugin.js里关掉

**Comment by LiuXIn011** [comment]
![image](https://github.com/LiuXIn011/rightHouse/assets/48080203/aad54eb4-f348-4027-a572-640e02a2b96a)
这个注释掉了全局的config都没了

**Comment by ugod3** [comment]
行，我把config,default修改的都取消了

**Comment by ugod3** [comment]
![图片](https://github.com/LiuXIn011/rightHouse/assets/53908829/07585808-96b3-4d3c-8d1b-f7e0aa6d04bc)
![图片](https://github.com/LiuXIn011/rightHouse/assets/53908829/af8e2e9b-6a84-44bd-a491-d3f1ccc6898a)
看报错显示的还是有参数没设置

**Comment by LiuXIn011** [comment]
配置改成什么样了

**Comment by LiuXIn011** [comment]
除了短信相关配置外，其他的配置建议都要全部填写，否则会出现很多意想不到的的错误。
例如这个地方，这个secret是必填的。
![image](https://github.com/LiuXIn011/rightHouse/assets/48080203/48be63d2-b98c-4d6d-9597-3fbbe876cf1d)

**Comment by ugod3** [comment]
好，我一个一个来吧，这个哪个插件的呢

**Comment by LiuXIn011** [comment]
jwt

**Comment by ugod3** [comment]
secret里面的内容是自定义的吗

**Comment by ugod3** [comment]
我自定义内容后启动是这样的
![图片](https://github.com/LiuXIn011/rightHouse/assets/53908829/f89922e1-a919-4138-88e1-4c3cbd86d56c)

**Comment by ugod3** [comment]
这些配置建议我应该填什么呢，研究了一会....还是不能启动出这个项目

**Comment by ugod3** [comment]
![图片](https://github.com/LiuXIn011/rightHouse/assets/53908829/e9f6f295-c6a8-4963-83f1-2865187fd39e)
前端目前是这样的

**Comment by LiuXIn011** [comment]
建议看一下文档，将配置除短信外全部填写

**Comment by ugod3** [comment]
行，我上次没注意到文档后面的部署，现在马上跟一下

**Comment by ugod3** [comment]
有windows的例子吗，有些命令执行不了，用windows的方法安装了。
在config.default.js内minio配置中endPoint填的是localhost吗，urldomain需要填什么

**Comment by ugod3** [comment]
/* eslint valid-jsdoc: "off" */

'use strict';

/**
 * @param {Egg.EggAppInfo} appInfo app info
 */
module.exports = appInfo => {
  const config = exports = {};
  config.keys = appInfo.name + '_1667378056410_2465';

  // 中间件列表
  config.middleware = [ 'errorHandler' ];
  // 错误处理中间件
  config.errorHandler = {
    match: '/api'
  };

  const userConfig = {
    // 房东端小程序配置
    landlordMP: {
      appid: '',
      secret: ''
    },
    // 租客端小程序配置
    tenantsMP: {
      appid: '',
      secret: ''
    },
    // 上传文件目录
    uploadDir: 'app/public/upload',
    // oss配置minio
    minio: {
      endPoint: 'localhost', // 连接地址
      port: 9000, // 端口
      useSSL: false, // 不需要https
      accessKey: 'tjjJ1CgkBfOi7Fp8gwsI',
      secretKey: 'N43IiSSkC6vxQPiGbN7iv59Bs92AWrzD4m08f9iI',
      urldomain: 'localhost:9000', // 域名
      bucketName: 'filebucket' // 桶名称
    },
    // 房间报修阿里云短信通知
    houseMaintenanceMessage: {
      SignName: '',
      TemplateCode: ''
    },
    // 房间维修完毕阿里云短信通知
    houseSolveMaintenanceMessage: {
      SignName: '',
      TemplateCode: ''
    },
    // 房间入住阿里云短信通知
    houseJoinTenantMessage: {
      SignName: '',
      TemplateCode: ''
    },
    // 房间退租给租客的阿里云短信通知
    houseOutTenantMessage: {
      SignName: '',
      TemplateCode: ''
    },
    // 房间退租给房东的阿里云短信通知
    houseOutLandlordMessage: {
      SignName: '',
      TemplateCode: ''
    },
    // 租客申请租赁的阿里云短信通知
    tenantLeaseApplicationMessage: {
      SignName: '',
      TemplateCode: ''
    },
    // 房东通过租赁的阿里云短信通知
    passLeaseApplicationMessage: {
      SignName: '',
      TemplateCode: ''
    },
    // 房东驳回租客租赁的阿里云短信通知
    nopassLeaseApplicationMessage: {
      SignName: '',
      TemplateCode: ''
    }
  };
  // 数据库配置
  config.sequelize = {
    dialect: 'mysql',
    host: 'localhost',
    port: 3306,
    database: 'right_house_db',
    username: 'root',
    password: 'root'
  };
  // redis配置
  config.redis = {
    client: {
      port: 6379,
      host: 'localhost',
      password: '',
      db: 0
    }
  };
  // security
  config.security = {
    csrf: {
      enable: false
    }
  };
  // jwt
  config.jwt = {
    secret: 'right',
    sign: {
      expiresIn: 604800 // 过期时间
    }
  };
  // multipart
  config.multipart = {
    mode: 'file'
  };
  // 默认配置
  config.cluster = {
    listen: {
      port: 80
    }
  };
  
  // 性能监控平台配置
  // config.alinode = {
  //   server: '',
  //   appid: '',
  //   secret: ''
  // };
  // 跨域配置
  config.cors = {
    origin: '*',
    allowMethods: 'GET,HEAD,PUT,POST,DELETE,PATCH'
  };

  // 短信服务配置
  config.sms = {
    client: {
      accessKeyId: '',
      secretAccessKey: ''
    }
  };
  return {
    ...config,
    ...userConfig
  };
};


这是现在的config.default.js，你看下配置的怎么样

**Comment by ugod3** [comment]
env文件
VITE_BASE_URL的接口访问地址是自定义的吗

**Comment by ugod3** [comment]
![image](https://github.com/LiuXIn011/rightHouse/assets/53908829/ed2bbfa8-a8e3-4dc4-a5a5-45870b85e3fa)
已经搭载在Nginx上了，
![image](https://github.com/LiuXIn011/rightHouse/assets/53908829/231349a1-9dc5-4493-a0ea-ecf1494b1397)
后端这样还差些什么呢
